image: node:20

stages:
  - prepare
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

prepare:
  stage: prepare
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1h

test:
  stage: test
  dependencies:
    - prepare
  script:
    - npm run test

build:
  stage: build
  dependencies:
    - prepare
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

deploy_ftp:
  stage: deploy
  image: alpine:3.20
  dependencies:
    - build
  before_script:
    - apk add --no-cache lftp
  script:
    - lftp -e "set ssl:verify-certificate no; open -u $FTP_USER,$FTP_PASS $FTP_HOST; mirror -R --delete dist/ $FTP_REMOTE_DIR; bye"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
