image: node:20

stages:
  - prepare
  - test
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

prepare:
  stage: prepare
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1h

test:
  stage: test
  dependencies:
    - prepare
  script:
    - npm run test

build:
  stage: build
  dependencies:
    - prepare
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
